"""
Vocabulary index contract.

docs/vocab/index.html is the human-readable entry point of the term
namespace. It is generated by pipeline/build_vocab_pages.py from the same
register the term pages come from (docs/vocab/klawiter.ttl), so these tests
pin the two properties that made the former hand-maintained index wrong:
the index covers exactly the registered terms, and it is deterministic.
"""

import re
from pathlib import Path

import build_vocab_pages as bvp

INDEX_PATH = Path(bvp.VOCAB_DIR) / "index.html"


def build() -> tuple[dict, str]:
    graph = bvp.load_graph()
    terms = bvp.collect_terms(graph)
    return terms, bvp.build_index(graph, terms)


def linked_terms(page: str) -> list[str]:
    """Term names of the generated term tables (prose links are excluded)."""
    return re.findall(r'<code><a href="([^"/]+)/">', page)


def test_index_links_exactly_the_registered_terms() -> None:
    terms, page = build()
    assert sorted(set(linked_terms(page))) == sorted(terms)


def test_index_links_every_term_once() -> None:
    _, page = build()
    linked = linked_terms(page)
    duplicates = {name for name in linked if linked.count(name) > 1}
    assert not duplicates


def test_index_covers_the_claim_layer() -> None:
    _, page = build()
    linked = set(linked_terms(page))
    claim_layer = {
        "ContestedClaim",
        "ClaimInterpretation",
        "ReviewAction",
        "WorkIdentityCandidate",
        "WikiInfrastructurePage",
        "sourceEvidence",
    }
    assert claim_layer <= linked


def test_index_is_byte_identical_across_builds() -> None:
    _, first = build()
    _, second = build()
    assert first == second


def test_index_carries_no_run_timestamp() -> None:
    _, page = build()
    assert "Last updated" not in page


def test_case_collisions_are_detected() -> None:
    assert bvp.case_collisions(["ReviewAction", "reviewAction", "evidence"]) == [
        ["ReviewAction", "reviewAction"]
    ]
    assert bvp.case_collisions(["ReviewAction", "evidence"]) == []


def test_committed_index_matches_the_generated_page() -> None:
    _, page = build()
    assert INDEX_PATH.read_text(encoding="utf-8") == page
